---
#123
- hosts: localhost
  vars_prompt:
     - name: aws_access_key
       prompt: "Enter AWS access key" # Prompt the user to enter the AWS access key
       private: no
     - name: aws_secret_key
       prompt: "Enter AWS secret key" # Prompt the user to enter the AWS secret key
       private: no
     - name: region
       prompt: "Enter the region" # Prompt the user to enter the AWS region
       private: no
  tasks:
     - name: Ensure boto existence
       pip:
        name:
          - boto3
          - botocore
        executable: pip3
        state: present # Ensure that the required Python packages (boto3, botocore) are installed

     - name: Creating Security Group
       amazon.aws.ec2_security_group:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         name: "high_az_sg" # Set the name of the security group
         description: Security Group for High AZ Server # Set the description of the security group
         region: "{{ region }}"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0 # Define inbound rules for SSH and HTTP traffic
         rules_egress:
           - proto: tcp
             from_port: 0
             to_port: 65535
             cidr_ip: 0.0.0.0/0 # Define an egress rule allowing all outbound traffic
       register: security_group # Store the security group information in the variable "security_group"

     - name: Creating ELB
       amazon.aws.elb_classic_lb:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        zones:
          - eu-central-1a
          - eu-central-1b
          - eu-central-1c # Specify the availability zones where the ELB will be created
        security_group_ids: "{{ security_group.group_id }}" # Assign the security group to the ELB
        name: "high-az-elb" # Set the name of the ELB

        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80 # Configure the ELB to listen on port 80 and forward traffic to instances on port 80

        health_check:
          ping_protocol: tcp
          ping_port: 80
          response_timeout: 5
          unhealthy_threshold: 2
          healthy_threshold: 2
          interval: 30 # Configure health checks for the ELB

        cross_az_load_balancing: "yes"
        idle_timeout: 400
        connection_draining_timeout: 400
        state: present # Create the ELB with the specified configuration
       register: elb # Store the ELB information in the variable "elb"

     - name: Set DNS Addresse
       set_fact:
        dns_address: "http://{{ elb.elb.dns_name }}" # Set the DNS address of the ELB

     - name: Display DNS Address
       debug:
          var: dns_address # Print the DNS address of the ELB

     - name: Creating launch configuration
       community.aws.autoscaling_launch_config:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "launch_config" # Set the name of the launch configuration
        image_id: "ami-04e601abe3e1a910f" # Set the ID of the Amazon Machine Image (AMI) to use
        key_name: "key_pair" # Set the name of the key pair to use for SSH access
        instance_type: "t2.micro" # Set the instance type for the Auto Scaling group
        region: "{{ region }}"
        security_groups: [ "{{ security_group.group_id }}" ] # Assign the security group to the launch configuration
        user_data: |
          #!/bin/bash
          # Update packages and install the Apache web server
          sudo apt update
          sudo apt install nginx -y

          # Get the instance metadata
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          INSTANCE_PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

          # Create a custom HTML page with instance details

          cat << EOF | sudo tee /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
              <title>Check High Availability</title>
          </head>
          <body>
              <h1>Hello from Instance $INSTANCE_ID</h1>
              <p>Public IP: $INSTANCE_PUBLIC_IP</p>
          </body>
          </html>
          EOF

          # Start and enable Apache to automatically start at boot time
          systemctl start nginx
          systemctl enable --now nginx
<<<<<<< HEAD:main.yaml
          systemctl restart apache2
        state: present # Create the launch configuration with the specified configuration
       register: lc_info # Store the launch configuration information in the variable "lc_info"
=======

        state: present
       register: lc_info
>>>>>>> 233e183 (updated):create.yaml

     - name: Creating Auto Scaling Group
       amazon.aws.autoscaling_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}" # Set the name of the Auto Scaling group
        name: "asGroup" # Set the name of the Auto Scaling group
        load_balancers: [ 'high-az-elb' ] # Associate the Auto Scaling group with the ELB
        availability_zones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"] # Specify the availability zones for the Auto Scaling group
        desired_capacity: 2 # Set the desired capacity (number of instances) for the Auto Scaling group
        launch_config_name: 'launch_config' # Specify the name of the launch configuration to use
        max_size: 2 # Set the maximum number of instances in the Auto Scaling group
        min_size: 1 # Set the minimum number of instances in the Auto Scaling group

     - name: Schedule for turning on instances
       community.aws.autoscaling_scheduled_action:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        scheduled_action_name: "turn_on"
        autoscaling_group_name: "asGroup"
        min_size: 1
        max_size: 3
        desired_capacity: 2
        recurrence: 0 8 * * *
        state: present
       register: turn_on

     - name: Schedule for turning off instances
       community.aws.autoscaling_scheduled_action:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        scheduled_action_name: "turn_off"
        autoscaling_group_name: "asGroup"
        min_size: 0
        max_size: 1
        desired_capacity: 0
        recurrence: 0 20 * * *
        state: present
       register: turn_off

     - name: Gather information about all instances
       amazon.aws.ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters:
           instance-state-name: ["running"] # Retrieve information about running instances
       register: ec2_info # Store the instance information in the variable "ec2_info
    
     - name: Display Public IP Addresses of instances
       debug:
          var: ec2_info.instances | map(attribute='public_ip_address') | list # Print the public IP addresses of the instances
